spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/personalProjectDB
    username: postgres
    password: 123456
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  main:
    allow-circular-references: true

jwt:
  lifetime: 10m
  secret: y9a8-u05j1kjahpsdiugf3479345dgajyx2357

